from shop.model import cart
from shop.model import cart_products
from shop.model import category
from shop.model import discount
from shop.model import discount_user
from shop.model import manufacturer
from shop.model import order
from shop.model import order_products
from shop.model import product
from shop.model import review
from shop.model import user
