# Generated by Django 3.0.12 on 2021-02-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('price', models.IntegerField()),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('code', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('available_to', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(default=None)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
                ('_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Manufacturer')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('price_per_item', models.IntegerField()),
                ('count', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.AddField(
            model_name='order',
            name='_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Discount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.BaseModel')),
                ('price_per_item', models.IntegerField()),
                ('count', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            bases=('shop.basemodel',),
        ),
        migrations.AddField(
            model_name='cart',
            name='_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
    ]
